language: c

script:
 - git submodule update --init
 - ./buildrump.sh/buildrump.sh -T rumptools -s rumpsrc -V NOSTATICLIB=1 -qq -j16 checkout fullbuild
 - (export NETMAPINCS=`pwd`/include ; cd libnetmapif ; ../rumptools/rumpmake MAKEVERBOSE=2 dependall && ../rumptools/rumpmake install)
 - (cd examples ; make )

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@lists.sourceforge.net
    on_success: always
    on_failure: always
